In [3]:
import streamlit as st
import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer, util
import fitz  # PyMuPDF

/home/codespace/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
job_vectors = np.load("job_vectors.npy")
jobs_df = pd.read_csv("all_job_offers.csv")

/tmp/ipykernel_49020/2563404436.py:2: DtypeWarning: Columns (17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  jobs_df = pd.read_csv("all_job_offers.csv")


In [37]:
model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')
resume_vector = model.encode("En tant qu'étudiant en Big Data et Intelligence Artificielle, je suis débutant je suis particulièrement bien qualifié avec Extraversion pour des rôles impliquant l'analyse de données et l'extraction d'informations pertinentes à partir de grandes quantités de données. Mes connaissances en Machine Learning me permettent également de travailler sur des projets de conception de modèles IA et/ou d’optimisation des paramètres de ces modèles.")
similarities = util.cos_sim(resume_vector, job_vectors)
top_results = np.argsort(-similarities[0])[:5]

In [38]:
similarities[0]

tensor([0.4576, 0.1570, 0.1556,  ..., 0.1290, 0.3411, 0.4102])

In [39]:
np.argsort(-similarities[0])[:5]

tensor([70266, 72612, 81010, 75839, 72734])

In [40]:
jobs_df.iloc[top_results]

job_title        city                     function  \
70266    Agri DataScientist  Ben guérir  Informatique / Electronique   
72612    Agri DataScientist  Ben guérir  Informatique / Electronique   
81010  Agri DataScientist 1   Benguerir                 Enseignement   
75839  Agri DataScientist 1   Benguerir                 Enseignement   
72734  Agri DataScientist 1   Benguerir                 Enseignement   

             sector Expérience requise                                 Région  \
70266  Informatique       De 3 à 5 ans  1 poste(s) sur Autres régions - Maroc   
72612  Informatique       De 3 à 5 ans  1 poste(s) sur Autres régions - Maroc   
81010  Informatique       De 3 à 5 ans  1 poste(s) sur Autres régions - Maroc   
75839  Informatique       De 3 à 5 ans  1 poste(s) sur Autres régions - Maroc   
72734  Informatique       De 3 à 5 ans  1 poste(s) sur Autres régions - Maroc   

      Niveau d'étude et formation Type de contrat Télétravail  \
70266              Bac +5 et plus             CDI          no   
72612              Bac +5 et plus             CDI          no   
81010              Bac +5 et plus             CDI     no info   
75839              Bac +5 et plus             CDI     no info   
72734              Bac +5 et plus             CDI          no   

                                             soft_skills  ...  \
70266  Besoin d'autonomie|Besoin de réflexion|Ambitio...  ...   
72612  Besoin d'autonomie|Besoin de réflexion|Ambitio...  ...   
81010  Extraversion|Organisation|Respect des règles|B...  ...   
75839  Recherche de nouveauté|Besoin de réflexion|Res...  ...   
72734  Extraversion|Organisation|Respect des règles|B...  ...   

      Qualités requises pour réussir dans ce rôle  \
70266                                         NaN   
72612                                         NaN   
81010                                         NaN   
75839                                         NaN   
72734                                         NaN   

      Ce que vous pouvez attendre de nous    pub_date    exp_date  \
70266                                 NaN  22/06/2022  22/08/2022   
72612                                 NaN  14/04/2022  14/06/2022   
81010                                 NaN  28/08/2021  28/10/2021   
75839                                 NaN  18/01/2022  18/03/2022   
72734                                 NaN  12/04/2022  12/06/2022   

      pub_date_day  pub_date_month pub_date_year exp_date_day exp_date_month  \
70266           22               6          2022           22              8   
72612           14               4          2022           14              6   
81010           28               8          2021           28             10   
75839           18               1          2022           18              3   
72734           12               4          2022           12              6   

      exp_date_year  
70266          2022  
72612          2022  
81010          2021  
75839          2022  
72734          2022  

[5 rows x 27 columns]

In [41]:
similarities[0][top_results]

tensor([0.7170, 0.7170, 0.7104, 0.7104, 0.7104])